### ISSUE TITLE
Unknown LTI/Shared secret users not getting added to internal groups

### ISSUE THREAD

**Issue by mrblippy** [apereo/openEQUELLA#588]
Steps to reproduce:
* Setup a new LTI consumer
* For Unknown user handling select 'Create local user and add them to the following groups...'
* Startup a selection session in your LMS of choice (I used moodle)
* The LMS user will be added as an internal equella user, but won't be added to the relevant group

**Comment by abidingotter** [comment]
This issue would only happen when all other attempts to fetch a user ID from the LTI parameters had failed.  Normally the LMS username or something else would be used, but due to certain options in the LMS then this information may not always come across.  
Equella falls back to generating a UUID for the user ID, however it was using a new UUID every time it added an ID to the tlegroup_users table.

**Comment by mrblippy** [comment]
Verified in 2019.1
